### ISSUE TITLE
 MySQL server has gone away

### ISSUE THREAD

**Issue by dmitry-tiger** [benvanstaveren/Mojolicious-Plugin-Database#4]
I use morbo server with Mojolicious::Plugin::Database
after long innactivity myqsl queries return error "DBD::mysql::st execute failed: MySQL server has gone away"

sub startup {
  my $self = shift;
  $self->setup_routing;
  $self->plugin('PODRenderer');
  my $config = $self->plugin('Config');
  $self->plugin('database', { 
    dsn      => 'dbi:mysql:dbname='.$self->{config}->{db}->{name}.';host='.$self->{config}->{db}->{host}.';port='.$self->{config}->{db}->{port},
    username => $self->{config}->{db}->{user},
    password => $self->{config}->{db}->{pass},
    options  => { AutoCommit => 1 },
    helper   => 'db',
    }); 
}

mojo version
CORE
  Perl        (v5.14.2, linux)
  Mojolicious (4.62, Top Hat)

OPTIONAL
  EV 4.0+               (not installed)
  IO::Socket::IP 0.16+  (not installed)
  IO::Socket::SSL 1.75+ (1.76)

Is this an issue?

**Comment by benvanstaveren** [comment]
Closing this issue - a rewrite is coming that will add some more functionality that should cover this issue soon
